local T, C, L, G = unpack(select(2, ...))
if G.Client == "zhCN" or G.Client == "zhTW" then return end

-- 安装
L["小泡泡"] = "Paopao"
L["欢迎使用"] = "Welcome to Altz UI Setup"
L["简介"] = "Altz UI is a minimalistic compilation with in-game configuration supported. Suggest taking a few minutes to quickly set up the addon."

L["上一步"] = "Previous"
L["下一步"] = "Next"
L["跳过"] = "Skip Setup Wizard"
L["设置向导"] = "Setup Wizard"
L["完成"] = "Finish"
L["更新日志"] = "Update Log"
L["更新日志tip"] = "New feature:\nUpdate for 10.00"
L["寻求帮助"] = "Help"
L["复制粘贴"] = "Ctrl+C/Ctrl+V copy/paste"
L["生效"] = " to take effect"
L["稍后重载"] = "Reload later"
L["脱离战斗"] = "Leave combat"

-- 控制台通用
L["界面"] = "Interface"
L["启用"] = "Enable"
L["显示"] = "Show"
L["隐藏"] = "Hide"
L["控制台"] = "GUI"
L["字体"] = "Font"
L["图标大小"] = "Icon Size"
L["图标数量"] = "Aura Number"
L["图标间距"] = "Icon Space"
L["缩放尺寸"] = "Scale"
L["字体大小"] = "Font Size"
L["数字大小"] = "Number size"
L["尺寸"] = "Size"
L["高度"] = "Height"
L["宽度"] = "Width"
L["光环"] = "Auras"
L["图标"] = "Icon"
L["Buffs"] = "Buffs"
L["Debuffs"] = "Debuffs"
L["输入法术ID"] = "Input a spellID"
L["不是一个有效的法术ID"] = "is not a correct spell ID"
L["左"] = "Left"
L["右"] = "Right"
L["上"] = "Up"
L["下"] = "Down"
L["中间"] = "Center"
L["左上"] = "Top Left"
L["右上"] = "Top Right"
L["左下"] = "Bottom Left"
L["右下"] = "Bottom Right"
L["上方"] = "Top"
L["下方"] = "Bottom"
L["垂直"] = "Vertical"
L["水平"] = "Horizontal"
L["正向"] = "Ascending"
L["反向"] = "Descending"
L["显示冷却"] = "Show %s's cooldown."
L["排列方向"] = "Anchor"
L["白名单"] = "Always display"
L["黑名单"] = "Never display"
L["时间"] = "Time"
L["减益"] = "Debuff"
L["增益"] = "Buff"

L["重置确认"] = "Do you want to reset all the %s settings?"
L["重置"] = "Reset"
L["导入确认"] = "Do you want to import all the %s settings?\n"
L["版本不符合"] = "\nImport Version %s（Current Version %s）"
L["客户端不符合"] = "\nGame Client %s（Current Client %s）"
L["职业不符合"] = "\nClass %s（Current Class %s）"
L["不完整导入"] = "\nMay not import completely."
L["导入"] = "Import"
L["导出"] = "Export"
L["无法导入"] = "Cannot Import"

-- 聊天
L["聊天按钮悬停渐隐"] = "Social Buttons Hover Fading"
L["聊天按钮悬停渐隐提示"] = "Enble button fading when your mouse is not hovering over them."
L["频道缩写"] = "Replace Channel Name"
L["滚动聊天框"] = "Scroll Chat Frame"
L["滚动聊天框提示"] = "Auto Scroll Chat Frame to bottom after a few seconds."
L["自动邀请"] = "Key Word Invite"
L["自动邀请提示"] = "Auto Invite people whispered key words"
L["关键词"] = "Key Word"
L["关键词输入"] = "Input key words separated by a space"
L["聊天过滤"] = "Chat Filter"
L["聊天过滤提示"] = "Hide repeated chat messages and chat messages containing key word(s) below."
L["过滤阈值"] = "Chat Filter Keyword Number"
L["显示聊天框背景"] = "Show background for chat frames."
L["复制聊天"] = "Copy Chat"
L["无法自动邀请进组:"] = "I can't invite you:"
L["我不能组人"] = "I'm not a raid leader or an assistant"
L["小队满了"] = "party is full"
L["团队满了"] = "raid is full"
L["客户端错误"] = "I can't invite you by keyword now, your account seems to be sticking to %s."

-- 背包和物品
L["启用背包模块"] = "Enable Inventory Mods"
L["背包图标大小"] = "Inventory icons size"
L["背包每行图标数量"] = "Inventory icon number per row"
L["自动修理"] = "Auto Repair"
L["自动修理提示"] = "Automatically repair items"
L["优先使用公会修理"] = "Auto Guild Repair"
L["优先使用公会修理提示"] = "Use Guild funds for auto repairs, use your own money when go over guild repair limit."
L["自动售卖"] = "Auto Sell"
L["自动售卖提示"] = "Automatically sell greys"
L["已会配方着色"] = "Colorizes Known Items"
L["已会配方着色提示"] = "Colorizes the item that is already known in some default frames."
L["自动购买"] = "Auto Buy"
L["自动购买提示"] = "Automatically buy items in the list below."
L["物品名称ID链接"] = "Item name/ID/link"
L["数量"] = "Quantity"
L["不正确的物品ID"] = "Incorrect Item name/ID/link"
L["不正确的数量"] = "Incorrect quantity"
L["赚得"] = "Earned:"
L["消费"] = "Spent:"
L["赤字"] = "Deficit:"
L["盈利"] = "Profit:"
L["本次登陆"] = "Session"
L["服务器"] = "Server"
L["角色"] = "Character"
L["重置金币信息"] = "Click to reset."
L["修理花费"] = "Repair Cost:"
L["购买"] = "Bought %d %s.%s"
L["每次最多购买"] = "Purchase up to %d at a time"
L["光标"] = "cursor"
L["当前"] = "current"

-- 单位框架
L["单位框架"] = "Unit Frames"
L["样式"] =  "Style"
L["总是显示生命值"] = "Always show HP"
L["总是显示生命值提示"] = "disable to show HP only when it's not full."
L["总是显示能量值"] = "Always show PP"
L["总是显示能量值提示"] = "disable to show PP only when it's not full."
L["数值字号"] = "Value fontsize"
L["数值字号提示"] = "HP and PP value fontsize"
L["肖像"] = "Portrait"
L["宽度提示"] = "The width for player, target and focus frame"
L["宠物框体宽度"] = "Pet Frame Width"
L["首领框体和PVP框体的宽度"] = "Boss Frame/Arena Frame Width"
--L["能量条高度"] = "PP Height"
L["施法条"] = "Castbar"
L["独立施法条"] = "Independent Castbar"
L["法术名称位置"] = "Spell Name Position"

L["施法时间位置"] = "Cast Duration Position"
L["引导法术分段"] = "Show every tick in a channel spell"
L["隐藏玩家施法条图标"] = "Hide the icon on player castbar"
L["平砍计时条"] = "Swing Timer"
L["过滤增益"] = "Target Aura Filter: Ignore Buff"
L["过滤增益提示"] = "Hide others' buff on friendly target."
L["过滤减益"] = "Target Aura Filter: Ignore Debuff"
L["过滤减益提示"] = "Hide others' debuffs on enemy target."
L["图腾条"] = "Totembar"
L["PvP标记"] = "PvP Icon"
L["PvP标记提示"] = "Recommand in a PvE Server"
L["启用首领框体"] = "Enable Bossframes"
L["启用PVP框体"] = "Enable Arenaframes"
L["在小队中显示自己"] = "Show player in party frames"
L["法力条"] = "mana bar"
L["法力条提示"] = "show mana bar for Dps Specialization"
L["启用仇恨条"] = "show threat bar"
L["显示醉拳条"] = "show stagger bar"
L["的徽章冷却就绪"] = "'s TrinketPVP is ready"
L["使用了徽章"] = " uses TrinketPVP"

-- 团队框架
L["通用设置"] = "Common"
L["名字长度"] = "Name Length"
L["未进组时显示"] = "Show Solo"
L["团队规模"] = "Group Size"
L["40-man"] = "40-man"
L["30-man"] = "30-man"
L["20-man"] = "20-man"
L["10-man"] = "10-man"
L["治疗法力条"] = "Display the mana bars of healing duty players in the group"
L["治疗法力条高度"] = "Healing mana bar height"
L["GCD"] = "GCD Bar"
L["GCD提示"] = "Show GCD bar on raid frame."
L["缺失生命值"] = "Missing HP"
L["缺失生命值提示"] = "Display missing health when health is less than 90% \ nDisplay name when health is greater than 90%"
L["治疗和吸收预估"] = "Heal Prediction and Absorb effects"
L["治疗和吸收预估提示"] = "Show heal prediction bar and absorb bar on raid frame."
L["职业顺序"] = "Sort raid members by their class."
L["整体高度"] = "Number Per Line"
L["整体高度提示"] = "How many units do you want to show per line?"
L["点击施法"] = "Click-Cast"
L["Button1"] = "Left"
L["Button2"] = "Right"
L["Button3"] = "Middle"
L["Button4"] = "4"
L["Button5"] = "5"
L["MouseUp"] = "MouseUp"
L["MouseDown"] = "MouseDown"
L["打开菜单"] = "Toggle Menu"
L["不正确的法术名称"] = "Incorret Spell"
L["输入一个宏"] = "Enter a macro"
L["优先级"] = "Priority"
L["必须是一个数字"] = "should be a number."
L["主坦克和主助手"] = "tank icon and main assist icon"
L["主坦克和主助手提示"] = "show tank icon and main assist icon on raid frames"
L["治疗指示器"] = "Healer Indicators"
L["数字指示器"] = "Number-style Indicators"
L["图标指示器"] = "Icon-style Indicators"
L["团队减益"] = "Raid/Dungeon Debuff"
L["全局"] = "Global"
L["自动添加团队减益"] = "Automatically add newly discovered Raid&Dungeon debuffs to the list"
L["自动添加团队减益提示"] = "The newly-discovered Raid&Dungeon debuffs are automatically added to the list. You can delete the newly added debuffs from the debuff list, or disable them from being displayed through the debuff blacklist filter."
L["自动添加的图标层级"] = "Aura Priority"
L["团队工具"] = "RaidTools"
L["添加团队减益"] = "|cff7FFF00Raid Debuff added successfully|r %s %s"
L["杂兵"] = "Trash"
L["设置"] = "Edit"
L["删除并加入黑名单"] = "Delete and add to blacklist"
L["已删除并加入黑名单"] = "|cff7FFF00Deleted and added to blacklist:%s|r"

-- 动作条
L["向上排列"] = "Grow Bar Upwards"
L["向上排列说明"] = "This growns the bars upwards when in a horizontal layout"
L["显示冷却时间"] = "Show Cooldown Text"
L["冷却时间数字大小"] = "Cooldown Text Size"
L["冷却时间数字大小提示"] = "This value only affects cooldown frames which size is bigger than 25*25pixel,\n others have their appropriate sized text.\nNote that the cooldown text won't show if it's too small."
L["显示冷却时间提示"] = "Displaying cooldown text on action buttons, inventory items, etc."
L["显示冷却时间提示WA"] = "Displaying cooldown text on Weakauras displays"
L["不可用颜色"] = "Beyond distance action bar turns red"
L["不可用颜色提示"] = "Change the color of standard action buttons when they are out of range."
L["键位字体大小"] = "Keybind Text Font Size"
L["宏名字字体大小"] = "Macro Name Text Font Size"
L["可用次数字体大小"] = "Count Text Font Size"

L["条件渐隐"] = "Conditional Fading"
L["条件渐隐提示"] = "Enable Fading when you are not casting, not in combat,\ndon't have a target and got max health or max/min power, etc."
L["悬停渐隐"] = "Hover Fading"
L["悬停渐隐提示"] = "Enble Actionbar Fading when your mouse is not hovering over them."
L["渐隐透明度"] = "Fading Alpha"
L["渐隐透明度提示"] = "Fade-out minimum alpha"

L["主动作条"] = "MainActionbar"
L["额外动作条"] = "MultiActionBar"
L["额外动作条布局"] = "MultiActionBar Layout"
L["额外动作条间距"] = "Space"
L["额外动作条间距提示"] = "The space between the left part and the right part are (bar12's width + 2*space1).\nOnly available when you enable the 3x2x2 layout."
L["6*4布局"] = "Layout 6*4"
L["右侧额外动作条"] = "RightMultiActionBar"
L["宠物动作条"] = "Pet Actionbar"
L["5*2布局"] = "Layout 5*2"
L["5*2布局提示"] = "Use Layout 5*2 for Pet Actionbar, disable to use layout 10*1."
L["姿态/形态条"] = "Stance Bar"
L["离开载具按钮"] = "Leave Vehicle Button"
L["额外特殊按钮"] = "Extrabar Button"
L["横向动作条"] = "Horizontal RightMultiActionBar"

L["冷却提示"] = "Cooldown Alert"
L["透明度"] = "Alpha"

-- 姓名板
L["姓名板tip"] = "How do you want to display the nameplates?"
L["数字样式"] = "Numberic Style"
L["职业色-条形"] = "Class Color Bar"
L["深色-条形"] = "Dark Color Bar"
L["仇恨染色"] = "Enchat Threat Color to Nameplates."
L["我施放的光环"] = "Auras I casted"
L["其他人施放的光环"] = "Auras others casted"
L["全部隐藏"] = "Hide All"
L["过滤方式"] = "Filter Type"


L["玩家姓名板"] = "My Nameplate"

L["可打断"] = "Interruptible"
L["不可打断"] = "Not interruptible"
L["颜色"] = "Color"
L["数值"] = "Value"
L["百分比"] = "Perc"
L["条形样式"] = "Bar"
L["友方只显示名字"] = "Name-only on friendly units"
L["根据血量染色"] = "Color according to hp perc"
L["焦点染色"] = "Color focus target"
L["自定义能量"] = "The nameplate of the following NPCs displays an energy bar"
L["自定义颜色"] = "The nameplate of the following NPCs display custom colors"
L["输入npc名称"] = "Imput npc name"
L["添加自定义能量"] = "Add [%s] to Custom Nameplate Power List"
L["移除自定义能量"] = "Remove [%s] from Custom Nameplate Power List"
L["添加自定义颜色"] = "Add [%s] to Custom Nameplate Color List"
L["移除自定义颜色"] = "Remove |cff%02x%02x%02x[%s]|r from Custom Nameplate Color List"
L["替换自定义颜色"] = "Replace |cff%02x%02x%02x[%s]|r from Custom Nameplate Color List"

-- 鼠标提示
L["鼠标提示"] = "Game Tooltip"
L["法术编号"] = "SpellID"
L["物品编号"] = "ItemID"
L["战斗中隐藏"] = "Hide in Combat"
L["副本"] = "Instance"
L["评分层数"] = "Score（Highest Level）"

-- 战斗信息
L["战斗数字"] = "Combat Text"
L["滚动战斗数字"] = "Scrolling combat text"
L["承受伤害/治疗"] = "Received Healing/Damage Text"
L["输出伤害/治疗"] = "Output Healing/Damage Text"
L["数字缩写样式"] = "abbreviated style"
L["显示DOT"] = "Show Dot"
L["显示HOT"] = "Show Hot"
L["浮动战斗数字"] = "Blizzard combat text"
L["受到伤害"] = "Received Damage"
L["受到治疗"] = "Received Healing"
L["造成伤害和治疗"] = "OutPut Healing/Damage"

-- 其他
L["讯息提示"] = "Message prompt"	
L["辅助功能"] = "Auxiliary functions"
L["界面风格"] = "Color Theme"
L["界面风格tip"] = "How do you want to display the UnitFrames?"
L["透明样式"] = "Transparent Theme"
L["深色样式"] = "Dark Theme"
L["普通样式"] = "Classic Theme"
L["小地图尺寸"] = "Minimap Size"
L["系统菜单尺寸"] = "Micromenu Scale"
L["信息条尺寸"] = "Info Bar Scale"
L["整理小地图图标"] = "Collect minimapbuttons"
L["整理栏位置"] = "Finishing box position"
L["成就截图"] = "Achievement Shot"
L["成就截图提示"] = "Take a screenshot when you earn an achievement."
L["自动接受复活"] = "Accept Resurrects"
L["自动接受复活提示"] = "Accept Resurrects, only available when out of combat."
L["战场自动释放灵魂"] = "Releases Spirit in BG"
L["战场自动释放灵魂提示"] = "Releases your spirit in BG, Wintergrasp and Tol Barad."
L["隐藏错误提示"] = "Hide Errors"
L["隐藏错误提示提示"] = "Hide the red errors texts, like out of range, etc."
L["自动接受邀请"] = "Accept Invites"
L["自动接受邀请提示"] = "Accept invites from your friends or guild members."
L["自动交接任务"] = "Auto Quests"
L["自动交接任务提示"] = "Automatically receive and turn in quests. Hold down Shift to temporarily suppress this function."
L["显示插件使用小提示"] = "Show addon tips when afk"
L["显示插件使用小提示提示"] = "Show addon tips on bottom of the screen when afk"
L["出现了！"] = "spotted!"
L["稀有警报"] = "Vignette alert"
L["稀有警报提示"] = "Display the vignette-ids introduced with 5.0.4 (chests, rare mobs etc) with name and icon on screen."
L["任务栏闪动"] = "Flash task bar"
L["任务栏闪动提示"] = "Flashes the taskbar when you are alt-tabbed and Dungeon, LFR or BG queue pops up."
L["自动召宝宝"] = "Automatically summon a pet"
L["自动召宝宝提示"] = "Automatically summon a pet when you login, resurrect or leave vehicle."
L["优先偏爱宝宝"] = "Prioritize summoning preferred pets"
L["优先偏爱宝宝提示"] = "Prioritize summoning small pets set as preferred, otherwise randomly summon one."
L["随机奖励"] = "LFG RoleShortage Alert"
L["随机奖励提示"] = "Raid Warning alert when LFG RoleShortage Rewards are available; only available when solo."
L["在副本中收起任务追踪"] = "Collapse tracker in instances"
L["在副本中收起任务追踪提示"] = "Collapse ObjectiveTracker when entering an instances/battleground, expand it when you leave."
L["提升截图画质"] = "Upgrade Screenshot picture quality"
L["截图保存为tga格式"] = "Screenshot saved as TGA format"
L["暂离屏幕"] = "Hide interface when AFK"
L["自定义任务追踪"] = "Custom Objective Tracker"
L["自定义任务追踪提示"] = "Enable this if you are using a custom objective tracker addon.\n  (ex: Dugi Questing Essential, Kaliel's Tracker)"

-- 插件界面
L["当前经验"] = "Current: "
L["剩余经验"] = "Remaining: "
L["双倍"] = "Rested: "
L["声望"] = "Rep:"
L["剩余声望"] = "Remaining: "
L["占用前 %d 的插件"] = "Top %d AddOns"
L["自定义插件占用"] = "UI Memory usage"
L["所有插件占用"] = "Total incl. Blizzard"
L["脱装备"] = "Undress All"
L["一直显示插件按钮"] = "Always show addon buttons"
L["小地图按钮"]	= "Altz UI Button"

-- 插件提示
L["隐藏提示的提示"] = "You can re-enable these tips in Interface → Layout"
L["TIPS"] = {
	"Click the date on the minimap to open the calendar",
	"Right click on the minimap to open the minimap tracking menu",
	"Want to display the independent castbar? GUI → Unit Frames → Castbar → Independent player castbar",
	"Want to use a custom color of the nameplate of a specific unit? CTRL+click on the mob's dropdown menu and select,or GUI → Unit Nameplates → Custom",
	"/rl - reload UI",
	"/hb - Key Binding Mode",
	"Use SHIFT+Click to set your focus; it's available for unit frames",
	"Use ALT+Click to mill/prospect, disenchant, unlock instantly",
	"Press Tab to change between available channels when the edit box of the chat frame is activated",
	"Hold Ctrl, Alt or Shift to scroll chat frame to top/bottom.",
}

-- 界面移动
L["界面移动工具"] = "Frame Mover"
L["锚点"] = "Anchor"
L["锚点框体"] = "Anchor Frame"
L["重置位置"] = "Reset this frame to it's default position."
L["healer"] = "|cff76EE00Healer|r"
L["dpser"] = "|cffE066FFDps/Tank|r"
L["选中的框体"] = "CurrentFrame"
L["当前模式"] = "CurrentMode"
L["进入战斗锁定"] = "Entered combat, lock all frames."
L["锁定框体"] = "Lock all frames"
L["解锁框体"] = "Unlock all frames"
L["框体位置"] = "Frame Positions"
L["信息条"] = "Info Bar"
L["承受伤害"] = "Received\nDamage Text"
L["承受治疗"] = "Received\nHealing Text"
L["输出伤害"] = "Output\nDamage Text"
L["输出治疗"] = "Output\nHealing Text"
L["单位框架"] = "Unit Frame"
L["团队框架"] = "Raid Frame"
L["焦点"] = "Focus"
L["目标的目标"] = "ToT"
L["焦点的目标"] = "ToF"
L["玩家平砍计时条"] = "Player Swing Timer"
L["冷却提示"] = "Cooldown Alert"
L["多人坐骑控制框"] = "Vehicle Seat Indicator"
L["耐久提示框"] = "Durability Frame"
L["主菜单和背包"] = "Micro Button And Bags Bar"

-- 插件皮肤
L["界面布局"] = "Layout"
L["界面布局tip"] = "How do you want to layout the Interface?"
L["默认布局"] = "Default Layout"
L["极简布局"] = "Minimal Layout"
L["聚合布局"] = "Centralized layout"
L["插件皮肤"] = "Addon Skins"
L["更改设置"] = "Reset Addon"
L["更改设置提示"] = "Load default settings for this addon"
L["边缘装饰"] = "Strip Decoration"
L["两侧装饰"] = "Decoration on both sides"

-- 命令
L["命令"] = "Commands"
L["指令"] = [[
/rl - Reload UI
/Setup-Run the setup wizard
SHIFT+Click - set focus to current mouseover target
Ctrl+Click - add raid mark to current mouseover target
ALT+Click - Mill/Prospect/Disenchant/Unlock instantly
Tab - Change between available channels
]]

-- 制作
L["制作"] = "Credits"
L["制作说明"] = "AltzUI ver %s \n \n \n \n Paopao zhCN \n \n \n \n Thanks to \n \n %s \n and everyone who help me with this Compilations."
